### ISSUE TITLE
Don't require a change set for Changesets and Renovate's pull requests

### ISSUE THREAD

**Issue by martinnabhan** [apollo-server-integrations/apollo-server-integration-next#42]
Changesets and Renovate's pull requests' checks fail due to missing change sets. Since we don't need to add change sets for these changes we shouldn't run `changeset status` on branches starting with `changeset-release/` or `renovate/`. Might also be good to enable auto merge, like https://github.com/apollographql/apollo-server seems to be doing.

**Comment by martinnabhan** [comment]
#43 worked when I tried it out locally but doesn't seem to work after merging so I'm reopening this.
https://github.com/apollo-server-integrations/apollo-server-integration-next/actions/runs/3475492524/jobs/5809777768

**Comment by trevor-scheer** [comment]
We accomplish this in the server repo by conditionally running the Circle job, is there a GH action equivalent you can try?
```
  Changesets:
    docker:
    - image: cimg/base:stable
    steps:
      - run: echo Ensure there is at least one step
      - unless:
          condition:
            matches:
              pattern: "^changeset-release/.+$"
              value: << pipeline.git.branch >>
          steps:
            - setup-node
            - run: npm run changeset-check
 ```
